import { CinematicDetail } from "./types";

export const animeDetails: CinematicDetail[] = [
  {
    id: "barakamon",
    title: "Barakamon",
    synopsis:
      "Um jovem e talentoso calígrafo é exilado para uma pequena ilha após agredir um crítico. Lá, ele encontra inspiração e amizade entre os habitantes excêntricos.",
    year: 2014,
    creator: "Satsuki Yoshino",
    cover: "/assets/images/animes/barakamon-2014.jpg",
    cast: ["Daisuke Ono", "Suzuko Mimori", "Nozomi Furuki"],
    rating: 4,
    genre: ["Slice of Life", "Comédia"],
    duration: 23,
    type: "anime",
  },
  {
    id: "berserk",
    title: "Berserk",
    synopsis:
      "Guts, um guerreiro solitário conhecido como o Espadachim Negro, busca vingança contra seu antigo amigo Griffith, que o traiu e sacrificou seus companheiros por poder demoníaco.",
    year: 1997,
    creator: "Kentaro Miura",
    cover: "/assets/images/animes/berserk-1997.jpg",
    cast: ["Nobutoshi Canna", "Hiroaki Hirata", "Yuko Miyamura"],
    rating: 5,
    genre: ["Fantasia Sombria", "Ação", "Drama"],
    duration: 25,
    type: "anime",
  },
  {
    id: "cowboy-bebop",
    title: "Cowboy Bebop",
    synopsis:
      "No ano de 2071, caçadores de recompensas viajam pelo espaço em busca de criminosos perigosos, enfrentando seus próprios passados sombrios.",
    year: 1998,
    creator: "Shinichirō Watanabe",
    cover: "/assets/images/animes/cowboy-bebop-1998.jpg",
    cast: ["Kōichi Yamadera", "Unshō Ishizuka", "Megumi Hayashibara"],
    rating: 5,
    genre: ["Ação", "Ficção Científica", "Drama"],
    duration: 24,
    type: "anime",
  },
  {
    id: "bleach",
    title: "Bleach",
    synopsis:
      "Ichigo Kurosaki, um adolescente que consegue ver fantasmas, tem sua vida virada de cabeça para baixo quando se torna um 'Shinigami' (Deus da Morte) e assume os deveres de uma ceifeira de almas.",
    year: 2004,
    creator: "Tite Kubo",
    cover: "/assets/images/animes/bleach-2004.jpg",
    cast: ["Masakazu Morita", "Fumiko Orikasa", "Yuki Matsuoka"],
    rating: 4,
    genre: ["Ação", "Aventura", "Sobrenatural"],
    duration: 24,
    type: "anime",
  },
  {
    id: "durarara",
    title: "Durarara!!",
    synopsis:
      "Em Tóquio, em um distrito caótico e misterioso, rumores sobre gangues coloridas, um motociclista sem cabeça e a vida diária de diversos personagens se entrelaçam.",
    year: 2010,
    creator: "Ryohgo Narita",
    cover: "/assets/images/animes/durarara-2010.jpg",
    cast: ["Miyuki Sawashiro", "Toshiyuki Toyonaga", "Daisuke Ono"],
    rating: 4,
    genre: ["Ação", "Mistério", "Sobrenatural"],
    duration: 24,
    type: "anime",
  },
  {
    id: "fairy-tail",
    title: "Fairy Tail",
    synopsis:
      "Lucy Heartfilia, uma maga celestial, se junta à guilda Fairy Tail e embarca em inúmeras aventuras com seus novos amigos, Natsu, Gray, Erza e Happy.",
    year: 2014,
    creator: "Hiro Mashima",
    cover: "/assets/images/animes/fairy-tail-2014.jpg",
    cast: ["Tetsuya Kakihara", "Aya Hirano", "Rie Kugimiya"],
    rating: 4,
    genre: ["Aventura", "Fantasia", "Ação"],
    duration: 24,
    type: "anime",
  },
  {
    id: "fullmetal-alchemist",
    title: "Fullmetal Alchemist",
    synopsis:
      "Os irmãos alquimistas Edward e Alphonse Elric buscam a Pedra Filosofal para restaurar seus corpos após uma tentativa fracassada de ressuscitar sua mãe.",
    year: 2003,
    creator: "Hiromu Arakawa",
    cover: "/assets/images/animes/fullmetal-alchemist-2003.jpg",
    cast: ["Romi Park", "Rie Kugimiya", "Megumi Toyoguchi"],
    rating: 5,
    genre: ["Aventura", "Fantasia", "Ação"],
    duration: 25,
    type: "anime",
  },
  {
    id: "gintama",
    title: "Gintama",
    synopsis:
      "Em um Japão feudal invadido por alienígenas, Gintoki Sakata, um samurai preguiçoso e viciado em açúcar, realiza trabalhos estranhos para sobreviver, levando a situações hilárias e emocionantes.",
    year: 2006,
    creator: "Hideaki Sorachi",
    cover: "/assets/images/animes/gintama-2006.jpg",
    cast: ["Tomokazu Sugita", "Daisuke Sakaguchi", "Rie Kugimiya"],
    rating: 5,
    genre: ["Comédia", "Ação", "Ficção Científica"],
    duration: 24,
    type: "anime",
  },
  {
    id: "great-teacher-onizuka",
    title: "Great Teacher Onizuka",
    synopsis:
      "Eikichi Onizuka, um ex-líder de gangue, decide se tornar o maior professor do mundo, usando métodos não convencionais para lidar com alunos problemáticos e superar os desafios do sistema educacional.",
    year: 1999,
    creator: "Tohru Fujisawa",
    cover: "/assets/images/animes/great-teacher-onizuka-1999.jpg",
    cast: ["Wataru Takagi", "Kotono Mitsuishi", "Tomoko Kawakami"],
    rating: 5,
    genre: ["Comédia", "Slice of Life", "Drama"],
    duration: 25,
    type: "anime",
  },
  {
    id: "gunsmith-cats",
    title: "Gunsmith Cats",
    synopsis:
      "Rally Vincent e Minnie May Hopkins, duas caçadoras de recompensas em Chicago, se envolvem em perseguições explosivas, tiroteios intensos e intrigas criminosas, tudo enquanto mantêm sua loja de armas, a 'Gunsmith Cats'.",
    year: 1995,
    creator: "Kenichi Sonoda",
    cover: "/assets/images/animes/gunsmith-cats-1995.jpg",
    cast: ["Michie Tomizawa", "Akemi Okamura", "Gara Takashima"],
    carouselImages: ["/assets/images/gunsmith-cats-banner.png"],
    rating: 4,
    genre: ["Ação", "Crime", "Aventura", "Comédia"],
    duration: 30,
    type: "anime",
    galleryImages: [
      {
        id: "1",
        title: "Rally Vincent",
        src: "/assets/images/gallery/gunsmith-cats/01.jpeg",
        description:
          "Rally Vincent, a atiradora habilidosa e protagonista de Gunsmith Cats",
        photoCredit: "aniDB",
        sourceLink: "https://anidb.net/character/17243",
        people: ["Michie Tomizawa (Voz de Rally Vincent)"],
      },
      {
        id: "2",
        title: "Minnie May Hopkins",
        src: "/assets/images/gallery/gunsmith-cats/02.png",
        description:
          "Minnie May Hopkins, a especialista em explosivos e parceira de Rally.",
        photoCredit: "Reddit",
        sourceLink:
          "https://www.reddit.com/r/GunsmithCats/comments/1cj0a81/i_know_a_ton_of_yall_like_rally_but_what_about/",
        people: ["Akemi Okamura (Voz de Minnie May Hopkins)"],
      },
      {
        id: "3",
        title: "Rally, May e Becky",
        src: "/assets/images/gallery/gunsmith-cats/03.png",
        description:
          "Rally, May e Becky observando as informações que estão na tela de um computador.",
        photoCredit: "aniSearch",
        sourceLink: "https://www.anisearch.com/",
        people: [
          "Michie Tomizawa (Rally Vincent)",
          "Akemi Okamura (Minnie May Hopkins)",
          "Yuko Mita (Voz de Becky Farrah)",
        ],
      },
      {
        id: "4",
        title: "Becky Farrah",
        src: "/assets/images/gallery/gunsmith-cats/04.jpg",
        description:
          "Becky Farrah, a informante e amiga que ajuda Rally e May com informações.",
        photoCredit: "Fandom",
        sourceLink: "https://www.fandom.com",
        people: ["Yuko Mita (Voz de Becky Farrah)"],
      },
      {
        id: "5",
        title: "Becky Farrah e Minnie May Hopkins",
        src: "/assets/images/gallery/gunsmith-cats/05.png",
        description: "Becky Farrah ajudando a May a subir no carro.",
        photoCredit: "aniSearch",
        sourceLink: "https://www.anisearch.com/",
        people: [
          "Akemi Okamura (Minnie May Hopkins)",
          "Yuko Mita (Voz de Becky Farrah)",
        ],
      },
    ],
  },
  {
    id: "katekyou-hitman-reborn",
    title: "Katekyou Hitman Reborn!",
    synopsis:
      "Tsunayoshi Sawada, um estudante desajeitado, descobre que é o décimo chefe da Família Vongola e é treinado por um bebê hitman chamado Reborn para se tornar um líder digno.",
    year: 2006,
    creator: "Akira Amano",
    cover: "/assets/images/animes/katekyou-hitman-reborn-2006.jpg",
    cast: ["Yukari Kokubun", "Neeko", "Hidekatsu Shibata"],
    rating: 4,
    genre: ["Ação", "Comédia", "Sobrenatural"],
    duration: 24,
    type: "anime",
  },
  {
    id: "kill-la-kill",
    title: "Kill la Kill",
    synopsis:
      "Ryuko Matoi busca a verdade por trás da morte de seu pai em uma academia onde a hierarquia é determinada por uniformes que concedem superpoderes, enfrentando a presidente Satsuki Kiryuin.",
    year: 2013,
    creator: "Hiroyuki Imaishi",
    cover: "/assets/images/animes/kill-la-kill-2013.jpg",
    cast: ["Ami Koshimizu", "Ryoka Yuzuki", "Toshihiko Seki"],
    rating: 4,
    genre: ["Ação", "Comédia", "Ficção Científica"],
    duration: 24,
    type: "anime",
  },
  {
    id: "little-witch-academia",
    title: "Little Witch Academia",
    synopsis:
      "Akko Kagari, uma garota comum que sonha em se tornar uma bruxa, se matricula na Luna Nova Magical Academy e, apesar de não ter habilidades mágicas, está determinada a seguir os passos de seu ídolo, Shiny Chariot.",
    year: 2017,
    creator: "Yoh Yoshinari",
    cover: "/assets/images/animes/little-witch-academia-2017.jpg",
    cast: ["Megumi Han", "Fumiko Orikasa", "Michiyo Murase"],
    rating: 4,
    genre: ["Fantasia", "Aventura", "Comédia"],
    duration: 24,
    type: "anime",
  },
  {
    id: "perfect-blue",
    title: "Perfect Blue",
    synopsis:
      "Mima Kirigoe, uma idol pop, decide mudar para uma carreira de atriz, mas logo começa a ser perseguida por um fã obsessivo e sua sanidade se deteriora à medida que a linha entre a realidade e a fantasia se desfaz.",
    year: 1998,
    creator: "Satoshi Kon",
    cover: "/assets/images/animes/perfect-blue-1998.jpg",
    cast: ["Junko Iwao", "Rika Matsumoto", "Masaaki Ōkura"],
    rating: 5,
    genre: ["Thriller", "Psicológico", "Drama"],
    duration: 81,
    type: "anime",
  },
  {
    id: "steins-gate",
    title: "Steins;Gate",
    synopsis:
      "Um grupo de amigos descobre uma maneira de enviar mensagens para o passado, desencadeando consequências inesperadas na linha do tempo.",
    year: 2011,
    creator: "Hiroshi Hamasaki",
    cover: "/assets/images/animes/steins-gate-2011.jpg",
    cast: ["Mamoru Miyano", "Kana Hanazawa", "Tomokazu Seki"],
    rating: 5,
    genre: ["Ficção Científica", "Drama", "Thriller"],
    duration: 24,
    type: "anime",
  },
];
