import { CinematicDetail } from "./types";

export const movieDetails: CinematicDetail[] = [
  {
    id: "a-time-to-kill",
    title: "A Time to Kill",
    synopsis:
      "Um jovem advogado defende um homem negro acusado de assassinar dois homens brancos que estupraram sua filha de 10 anos, provocando o renascimento da Ku Klux Klan.",
    year: 1996,
    creator: "Joel Schumacher",
    cover: "/assets/images/movies/a-time-to-kill-1996.jpg",
    cast: [
      "Matthew McConaughey",
      "Sandra Bullock",
      "Samuel L. Jackson",
      "Kevin Spacey",
    ],
    carouselImages: ["/assets/images/a-time-to-kill-banner.jpg"],
    rating: 4,
    genre: ["Drama", "Crime", "Thriller"],
    duration: 149,
    galleryImages: [
      {
        id: "1",
        title: "Cena do Tribunal",
        src: "https://m.media-amazon.com/images/M/MV5BMTc1MTU0MDMyMl5BMl5BanBnXkFtZTgwMTM3NzY3MTE@._V1_.jpg",
        description: "Sandra Bullock e Matthew McConaughey em 1996",
        photoCredit: "Warner Bros Pictures",
        sourceLink: "https://warnerbros.com",
        people: ["Sandra Bullock", "Matthew McConaughey (Jake Brigance)"],
      },
      {
        id: "2",
        title: "Cena da Cela",
        src: "https://images.squarespace-cdn.com/content/v1/5a5806c380bd5ee5f0228040/1529034932371-CKMEK6YXZFVTX2I7DG0B/ttk+4.jpg",
        description: "Samuel L. Jackson e Matthew McConaughey",
        photoCredit: "Warner Bros Pictures",
        sourceLink: "https://warnerbros.com",
        people: [
          "Samuel L. Jackson (Carl Lee Hailey)",
          "Matthew McConaughey (Jake Brigance)",
        ],
      },
      {
        id: "3",
        title: "Cena da Tribunal",
        src: "https://images.kinorium.com/movie/shot/106936/h280_49292506.jpg",
        description: "Matthew McConaughey e Samuel L. Jackson",
        photoCredit: "Warner Bros Pictures",
        sourceLink: "https://warnerbros.com",
        people: [
          "Matthew McConaughey (Jake Brigance)",
          "Samuel L. Jackson (Carl Lee Hailey)",
        ],
      },
      {
        id: "4",
        title: "Cena da Familia do Matthew McConaughey",
        src: "https://www.shutterstock.com/editorial/image-editorial/N1Tbk0ydN9DaA9yaNjQyNg==/matthew-mcconaughey-ashley-judd-440nw-5883852h.jpg",
        description: "Matthew McConaughey e sua familia",
        photoCredit: "Warner Bros Pictures",
        sourceLink: "https://warnerbros.com",
        people: ["Matthew McConaughey (Jake Brigance)"],
      },
      {
        id: "5",
        title: "Cena do Tribunal",
        src: "https://static0.srcdn.com/wordpress/wp-content/uploads/2022/10/Matthew-McConaughey-in-court-in-A-Time-to-Kill.jpg?q=50&fit=crop&w=825&dpr=1.5",
        description: "Matthew McConaughey no Tribunal",
        photoCredit: "Warner Bros Pictures",
        sourceLink: "https://warnerbros.com",
        people: ["Matthew McConaughey (Jake Brigance)"],
      },
    ],
    type: "movie",
  },
  {
    id: "the-godfather",
    title: "The Godfather",
    synopsis:
      "A saga da família mafiosa Corleone, que luta para manter o poder em meio a traições, guerras entre famílias rivais e mudanças na sociedade americana.",
    year: 1972,
    creator: "Francis Ford Coppola",
    cover: "/assets/images/movies/the-godfather-1972.jpg",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
    rating: 5,
    genre: ["Crime", "Drama"],
    duration: 175,
    type: "movie",
  },
  {
    id: "fallen-angels",
    title: "Fallen Angels",
    synopsis:
      "Em Hong Kong, um matador profissional tenta deixar sua vida de crimes, enquanto uma mulher muda seu caminho para se tornar sua agente. Um solitário muda fechado encontra um amor não correspondido.",
    year: 1995,
    creator: "Wong Kar-wai",
    cover: "/assets/images/movies/fallen-angels-1995.jpg",
    cast: ["Leon Lai", "Michelle Reis", "Takeshi Kaneshiro", "Charlie Yeung"],
    rating: 4,
    genre: ["Crime", "Drama", "Romance"],
    duration: 98,
    type: "movie",
  },
  {
    id: "amadeus",
    title: "Amadeus",
    synopsis:
      "A vida do compositor Wolfgang Amadeus Mozart é narrada por seu invejoso rival, Antonio Salieri, que busca vingança divina contra o gênio de Mozart.",
    year: 1984,
    creator: "Miloš Forman",
    cover: "/assets/images/movies/amadeus-1984.jpg",
    cast: ["F. Murray Abraham", "Tom Hulce", "Elizabeth Berridge"],
    rating: 5,
    genre: ["Biografia", "Drama", "Música"],
    duration: 160,
    type: "movie",
  },
  {
    id: "john-wick-2",
    title: "John Wick: Chapter 2",
    synopsis:
      "O lendário assassino de aluguel John Wick é forçado a sair da aposentadoria por um antigo juramento. Ele viaja para Roma para enfrentar alguns dos assassinos mais mortais do mundo.",
    year: 2017,
    creator: "Chad Stahelski",
    cover: "/assets/images/movies/john-wick-chapter-2-2017.jpg",
    cast: ["Keanu Reeves", "Common", "Laurence Fishburne", "Ruby Rose"],
    rating: 4,
    genre: ["Ação", "Thriller", "Crime"],
    duration: 122,
    type: "movie",
  },
  {
    id: "ip-man",
    title: "Ip Man",
    synopsis:
      "A vida de Ip Man, um mestre de Wing Chun que se recusa a ensinar suas artes marciais para os japoneses durante a Segunda Guerra Sino-Japonesa, protegendo sua comunidade.",
    year: 2008,
    creator: "Wilson Yip",
    cover: "/assets/images/movies/ip-man-2008.jpg",
    cast: ["Donnie Yen", "Simon Yam", "Lynn Hung", "Hiroyuki Ikeuchi"],
    rating: 4,
    genre: ["Ação", "Biografia", "Drama"],
    duration: 106,
    type: "movie",
  },
  {
    id: "shawshank-redemption",
    title: "Shawshank Redemption",
    synopsis:
      "Dois homens presos encontram consolo e redenção através de atos de decência comum ao longo de anos de encarceramento em uma prisão brutal.",
    year: 1994,
    creator: "Frank Darabont",
    cover: "/assets/images/movies/the-shawshank-redemption-1994.jpg",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    rating: 5,
    genre: ["Drama"],
    duration: 142,
    type: "movie",
  },
  {
    id: "butterfly-effect",
    title: "Butterfly Effect",
    synopsis:
      "Evan Treborn, um jovem com a capacidade de viajar no tempo para momentos cruciais de sua infância, tenta mudar o passado para melhorar o presente, mas descobre que cada mudança tem consequências imprevisíveis.",
    year: 2004,
    creator: "Eric Bress, J. Mackye Gruber",
    cover: "/assets/images/movies/the-butterfly-effect-2004.jpg",
    cast: ["Ashton Kutcher", "Amy Smart", "Elden Henson"],
    rating: 4,
    genre: ["Ficção Científica", "Thriller", "Drama"],
    duration: 113,
    type: "movie",
  },
  {
    id: "imitation-game",
    title: "The Imitation Game",
    synopsis:
      "Durante a Segunda Guerra Mundial, o brilhante matemático Alan Turing lidera uma equipe para decifrar o código Enigma alemão, salvando milhões de vidas, mas enfrentando perseguição por sua homossexualidade.",
    year: 2014,
    creator: "Morten Tyldum",
    cover: "/assets/images/movies/the-imitation-game-2014.jpg",
    cast: ["Benedict Cumberbatch", "Keira Knightley", "Matthew Goode"],
    rating: 4,
    genre: ["Biografia", "Drama", "Guerra"],
    duration: 114,
    type: "movie",
  },
  {
    id: "parasite",
    title: "Parasite",
    synopsis:
      "A família Kim, pobre e astuta, infiltra-se na casa de uma rica família de Seul, levando a uma série de acontecimentos inesperados e sombrios.",
    year: 2019,
    creator: "Bong Joon-ho",
    cover: "/assets/images/movies/parasite-2019.jpg",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    rating: 5,
    genre: ["Drama", "Thriller"],
    duration: 132,
    type: "movie",
  },
  {
    id: "back-to-the-future",
    title: "Back To The Future",
    synopsis:
      "Marty McFly, um adolescente, acidentalmente viaja de volta no tempo para 1955 em um DeLorean modificado por um cientista excêntrico e deve garantir que seus pais se apaixonem para que ele possa existir.",
    year: 1985,
    creator: "Robert Zemeckis",
    cover: "/assets/images/movies/back-to-the-future-1985.jpg",
    cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"],
    rating: 5,
    genre: ["Aventura", "Comédia", "Ficção Científica"],
    duration: 116,
    type: "movie",
  },
  {
    id: "beverly-hills-cop",
    title: "Beverly Hills Cop",
    synopsis:
      "O detetive de Detroit Axel Foley viaja para Beverly Hills, Califórnia, para investigar o assassinato de um amigo e se depara com um mundo de luxo e crime.",
    year: 1984,
    creator: "Martin Brest",
    cover: "/assets/images/movies/beverly-hills-cop-1984.jpg",
    cast: ["Eddie Murphy", "Judge Reinhold", "John Ashton"],
    rating: 4,
    genre: ["Ação", "Comédia", "Crime"],
    duration: 105,
    type: "movie",
  },
  {
    id: "escape-from-new-york",
    title: "Escape From New York",
    synopsis:
      "No futuro distópico de 1997, a ilha de Manhattan foi convertida em uma prisão de segurança máxima. Quando o avião do presidente cai lá, o ex-soldado Snake Plissken é enviado para resgatá-lo.",
    year: 1981,
    creator: "John Carpenter",
    cover: "/assets/images/movies/escape-from-new-york-1981.jpg",
    cast: ["Kurt Russell", "Lee Van Cleef", "Ernest Borgnine"],
    rating: 4,
    genre: ["Ação", "Ficção Científica", "Thriller"],
    duration: 99,
    type: "movie",
  },
  {
    id: "road-house",
    title: "Road House",
    synopsis:
      "Dalton, um segurança lendário e filósofo, é contratado para restaurar a ordem em um bar noturno rústico no Missouri, enfrentando um empresário corrupto e sua gangue.",
    year: 1989,
    creator: "Rowdy Herrington",
    cover: "/assets/images/movies/road-house-1989.jpg",
    cast: ["Patrick Swayze", "Kelly Lynch", "Sam Elliott"],
    rating: 3,
    genre: ["Ação", "Thriller"],
    duration: 114,
    type: "movie",
  },
  {
    id: "they-live",
    title: "They Live",
    synopsis:
      "Um andarilho descobre um par de óculos de sol que revela a verdade sobre a sociedade: alienígenas estão se disfarçando como humanos e controlando a população através de mensagens subliminares na mídia.",
    year: 1988,
    creator: "John Carpenter",
    cover: "/assets/images/movies/they-live-1988.jpg",
    cast: ["Roddy Piper", "Keith David", "Meg Foster"],
    rating: 4,
    genre: ["Ficção Científica", "Ação", "Thriller"],
    duration: 94,
    type: "movie",
  },
];
