import { CinematicDetail } from "./types";

export const serieDetails: CinematicDetail[] = [
  {
    id: "the-x-files",
    title: "The X-Files",
    synopsis:
      "Os agentes do FBI Fox Mulder e Dana Scully investigam casos misteriosos e paranormais conhecidos como Arquivos X.",
    year: 1993,
    creator: "Chris Carter",
    cover: "/assets/images/series/the-x-files-1993.jpg",
    cast: ["David Duchovny", "Gillian Anderson", "Mitch Pileggi"],
    carouselImages: ["/assets/images/the-x-files-banner.jpg"],
    rating: 4,
    genre: ["Mistério", "Ficção Científica", "Drama"],
    duration: 45,
    galleryImages: [
      {
        id: "1",
        title: "Agente Scully",
        src: "/assets/images/gallery/the-x-files/01.png",
        description: "Gillian Anderson em Arquivo X (1993)",
        photoCredit: "20th Century Fox",
        sourceLink: "https://www.20thcenturystudios.com",
        people: ["Gillian Anderson (Dana Scully)"],
      },
      {
        id: "2",
        title: "Agentes Mulder e Scully",
        src: "/assets/images/gallery/the-x-files/02.png",
        photoCredit: "20th Century Fox",
        sourceLink: "https://www.20thcenturystudios.com",
        people: [
          "David Duchovny (Fox Mulder)",
          "Gillian Anderson (Dana Scully)",
        ],
      },
      {
        id: "3",
        title: "Agentes Mulder e Scully",
        src: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2015/03/25/19/38-X-Files.jpg",
        people: [
          "David Duchovny (Fox Mulder)",
          "Gillian Anderson (Dana Scully)",
        ],
      },
      {
        id: "4",
        title: "Agentes Mulder e Scully",
        src: "https://cleigh6.tripod.com/CTP/CTP%20PICS/Screenshot021-1.jpg",
        people: [
          "David Duchovny (Fox Mulder)",
          "Gillian Anderson (Dana Scully)",
        ],
      },
      {
        id: "5",
        title: "Agentes Mulder e Scully",
        src: "https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2010/4/13/1271167492002/x-files-notes-and-queries-001.jpg?width=460&quality=85&auto=format&fit=max&s=eb85e5520f47dba089326e21e8dbd79c",
        people: [
          "David Duchovny (Fox Mulder)",
          "Gillian Anderson (Dana Scully)",
        ],
      },
    ],
    type: "serie",
    seasons: [
      {
        id: "the-x-files-s1",
        seasonNumber: 1,
        title: "Temporada 1",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/01.jpg",
        episodes: 24,
        releaseYear: 1993,
        highlights: ["Primeiro caso paranormal", "Mulder e Scully se conhecem"],
      },
      {
        id: "the-x-files-s2",
        seasonNumber: 2,
        title: "Temporada 2",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/02.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s3",
        seasonNumber: 3,
        title: "Temporada 3",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/03.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s4",
        seasonNumber: 4,
        title: "Temporada 4",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/04.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s5",
        seasonNumber: 5,
        title: "Temporada 5",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/05.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s6",
        seasonNumber: 6,
        title: "Temporada 6",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/06.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s7",
        seasonNumber: 7,
        title: "Temporada 7",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/07.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s8",
        seasonNumber: 8,
        title: "Temporada 8",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/08.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s9",
        seasonNumber: 9,
        title: "Temporada 9",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/09.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s10",
        seasonNumber: 10,
        title: "Temporada 10",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/10.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
      {
        id: "the-x-files-s11",
        seasonNumber: 11,
        title: "Temporada 11",
        synopsis:
          "Os agentes Fox Mulder e Dana Scully são designados para os Arquivos X, investigando casos inexplicáveis. Eles se deparam com conspirações governamentais e fenômenos paranormais.",
        cover: "/assets/images/season/the-x-files/11.jpg",
        episodes: 25,
        releaseYear: 1994,
      },
    ],
  },
  {
    id: "13-reasons-why",
    title: "13 Reasons Why",
    synopsis:
      "Após o suicídio de uma colega de escola, Clay Jensen recebe uma caixa de fitas cassete gravadas por ela, revelando os treze motivos que a levaram a tirar a própria vida.",
    year: 2017,
    creator: "Brian Yorkey",
    cover: "/assets/images/series/13-reasons-why-2017.jpg",
    cast: ["Dylan Minnette", "Katherine Langford", "Christian Navarro"],
    rating: 3,
    genre: ["Drama", "Mistério"],
    duration: 60,
    type: "serie",
  },
  {
    id: "breaking-bad",
    title: "Breaking Bad",
    synopsis:
      "Um professor de química do ensino médio, diagnosticado com câncer terminal, começa a fabricar metanfetamina para garantir o futuro de sua família.",
    year: 2008,
    creator: "Vince Gilligan",
    cover: "/assets/images/series/breaking-bad-2008.png",
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Dean Norris"],
    rating: 5,
    genre: ["Crime", "Drama", "Thriller"],
    duration: 47,
    type: "serie",
  },
  {
    id: "cobra-kai",
    title: "Cobra Kai",
    synopsis:
      "Décadas após o torneio de karatê de 1984, Johnny Lawrence reabre o dojo Cobra Kai, reacendendo sua rivalidade com Daniel LaRusso.",
    year: 2018,
    creator: "Josh Heald, Jon Hurwitz, Hayden Schlossberg",
    cover: "/assets/images/series/cobra-kai-2018.jpg",
    cast: ["William Zabka", "Ralph Macchio", "Courtney Henggeler"],
    rating: 4,
    genre: ["Ação", "Comédia", "Drama"],
    duration: 30,
    type: "serie",
  },
  {
    id: "disenchantment",
    title: "Disenchantment",
    synopsis:
      "A princesa Bean, seu elfo companheiro Elfo e seu demônio pessoal Luci exploram o reino medieval de Dreamland, encontrando criaturas fantásticas e desventuras hilárias.",
    year: 2018,
    creator: "Matt Groening",
    cover: "/assets/images/series/disenchantment-2018.jpg",
    cast: ["Abbi Jacobson", "Nat Faxon", "Eric André"],
    rating: 3,
    genre: ["Animação", "Aventura", "Comédia"],
    duration: 30,
    type: "serie",
  },
  {
    id: "futurama",
    title: "Futurama",
    synopsis:
      "Philip J. Fry, um entregador de pizza, é acidentalmente congelado criogenicamente em 1999 e descongela no ano 3000, onde faz novos amigos e arranja um emprego na Planet Express.",
    year: 1999,
    creator: "Matt Groening",
    cover: "/assets/images/series/futurama-1999.jpg",
    cast: ["Billy West", "Katey Sagal", "John DiMaggio"],
    rating: 4,
    genre: ["Animação", "Comédia", "Ficção Científica"],
    duration: 22,
    type: "serie",
  },
  {
    id: "icarly",
    title: "iCarly",
    synopsis:
      "Carly Shay, uma adolescente, e seus amigos Sam e Freddie, criam um webshow de sucesso, vivendo aventuras e desventuras enquanto equilibram suas vidas escolares e o estrelato na internet.",
    year: 2007,
    creator: "Dan Schneider",
    cover: "/assets/images/series/icarly-2007.jpg",
    cast: ["Miranda Cosgrove", "Jennette McCurdy", "Nathan Kress"],
    rating: 3,
    genre: ["Comédia", "Família"],
    duration: 24,
    type: "serie",
  },
  {
    id: "rick-and-morty",
    title: "Rick and Morty",
    synopsis:
      "Um cientista genial, mas alcoólatra, Rick Sanchez, arrasta seu neto facilmente influenciável, Morty Smith, em aventuras perigosas e bizarras através do tempo e do espaço.",
    year: 2013,
    creator: "Dan Harmon, Justin Roiland",
    cover: "/assets/images/series/rick-and-morty-2013.png",
    cast: ["Justin Roiland", "Chris Parnell", "Spencer Grammer"],
    rating: 5,
    genre: ["Animação", "Aventura", "Comédia"],
    duration: 23,
    type: "serie",
  },
  {
    id: "smiling-friends",
    title: "Smiling Friends",
    synopsis:
      "Pim e Charlie, dois empregados da Smiling Friends Inc., são enviados para ajudar pessoas infelizes e bizarras a encontrar a felicidade.",
    year: 2022,
    creator: "Zach Hadel, Michael Cusack",
    cover: "/assets/images/series/smiling-friends-2022.jpg",
    cast: ["Michael Cusack", "Zach Hadel", "Marc M."],
    rating: 4,
    genre: ["Animação", "Comédia"],
    duration: 11,
    type: "serie",
  },
  {
    id: "squid-game",
    title: "Squid Game",
    synopsis:
      "Centenas de jogadores endividados aceitam um convite estranho para competir em jogos infantis, mas logo descobrem que a aposta é suas próprias vidas.",
    year: 2021,
    creator: "Hwang Dong-hyuk",
    cover: "/assets/images/series/squid-game-2021.jpg",
    cast: ["Lee Jung-jae", "Park Hae-soo", "Jung Ho-yeon"],
    rating: 4,
    genre: ["Ação", "Drama", "Suspense"],
    duration: 60,
    type: "serie",
  },
  {
    id: "stranger-things",
    title: "Stranger Things",
    synopsis:
      "Na pequena cidade de Hawkins, Indiana, um grupo de crianças enfrenta forças sobrenaturais após o desaparecimento de um amigo.",
    year: 2016,
    creator: "Irmãos Duffer",
    cover: "/assets/images/series/stranger-things-2016.jpg",
    cast: [
      "Millie Bobby Brown",
      "Finn Wolfhard",
      "David Harbour",
      "Winona Ryder",
    ],
    rating: 5,
    genre: ["Ficção Científica", "Terror", "Drama"],
    duration: 50,
    type: "serie",
  },
  {
    id: "supernatural",
    title: "Supernatural",
    synopsis:
      "Os irmãos Sam e Dean Winchester viajam pelos Estados Unidos caçando demônios, fantasmas e outras criaturas sobrenaturais, enquanto lidam com seu próprio passado trágico.",
    year: 2005,
    creator: "Eric Kripke",
    cover: "/assets/images/series/supernatural-2005.jpg",
    cast: ["Jared Padalecki", "Jensen Ackles", "Misha Collins"],
    rating: 4,
    genre: ["Fantasia", "Drama", "Terror"],
    duration: 42,
    type: "serie",
  },
  {
    id: "the-boys",
    title: "The Boys",
    synopsis:
      "Em um mundo onde super-heróis são celebridades corruptas, um grupo de vigilantes busca expor a verdade sobre a poderosa corporação Vought International e seus super-heróis.",
    year: 2019,
    creator: "Eric Kripke",
    cover: "/assets/images/series/the-boys-2019.jpg",
    cast: ["Karl Urban", "Jack Quaid", "Antony Starr"],
    rating: 5,
    genre: ["Ação", "Comédia", "Drama"],
    duration: 60,
    type: "serie",
  },
  {
    id: "the-simpsons",
    title: "The Simpsons",
    synopsis:
      "As aventuras e desventuras da família Simpson – Homer, Marge, Bart, Lisa e Maggie – em sua vida cotidiana na cidade de Springfield.",
    year: 1989,
    creator: "Matt Groening",
    cover: "/assets/images/series/the-simpsons-1989.jpg",
    cast: ["Dan Castellaneta", "Julie Kavner", "Nancy Cartwright"],
    rating: 4,
    genre: ["Animação", "Comédia"],
    duration: 22,
    type: "serie",
  },
  {
    id: "everybody-hates-chris",
    title: "Everybody Hates Chris",
    synopsis:
      "Chris Rock narra suas experiências de infância e adolescência crescendo em Bed-Stuy, Brooklyn, nos anos 80, enfrentando desafios na escola e em casa.",
    year: 2005,
    creator: "Chris Rock, Ali LeRoi",
    cover: "/assets/images/series/everybody-hates-chris-2005.jpg",
    cast: ["Tyler James Williams", "Terry Crews", "Tichina Arnold"],
    rating: 5,
    genre: ["Comédia", "Sitcom"],
    duration: 22,
    type: "serie",
  },
];
