import { Item } from "./types";

export const animeItems: Item[] = [
  {
    id: "barakamon",
    title: "Barakamon",
    poster: "/assets/images/animes/barakamon-2014.jpg",
    video: "/assets/videos/barakamon.mp4",
    type: "anime",
  },
  {
    id: "berserk",
    title: "Berserk",
    poster: "/assets/images/animes/berserk-1997.jpg",
    type: "anime",
  },
  {
    id: "cowboy-bebop",
    title: "Cowboy Bebop",
    poster: "/assets/images/animes/cowboy-bebop-1998.jpg",
    video: "/assets/videos/cowboy-bebop.mp4",
    type: "anime",
  },
  {
    id: "bleach",
    title: "Bleach",
    poster: "/assets/images/animes/bleach-2004.jpg",
    type: "anime",
  },
  {
    id: "durarara",
    title: "Durarara!!",
    poster: "/assets/images/animes/durarara-2010.jpg",
    video: "/assets/videos/durarara.mp4",
    type: "anime",
  },
  {
    id: "fairy-tail",
    title: "Fairy Tail",
    poster: "/assets/images/animes/fairy-tail-2014.jpg",
    type: "anime",
  },
  {
    id: "fullmetal-alchemist",
    title: "Fullmetal Alchemist",
    poster: "/assets/images/animes/fullmetal-alchemist-2003.jpg",
    type: "anime",
  },
  {
    id: "gintama",
    title: "Gintama",
    poster: "/assets/images/animes/gintama-2006.jpg",
    type: "anime",
  },
  {
    id: "great-teacher-onizuka",
    title: "Great Teacher Onizuka",
    poster: "/assets/images/animes/great-teacher-onizuka-1999.jpg",
    type: "anime",
  },
  {
    id: "gunsmith-cats",
    title: "Gunsmith Cats",
    poster: "/assets/images/animes/gunsmith-cats-1995.jpg",
    video: "/assets/videos/gunsmith-cats.mp4",
    type: "anime",
  },
  {
    id: "katekyou-hitman-reborn",
    title: "Katekyou Hitman Reborn!",
    poster: "/assets/images/animes/katekyou-hitman-reborn-2006.jpg",
    type: "anime",
  },
  {
    id: "kill-la-kill",
    title: "Kill la Kill",
    poster: "/assets/images/animes/kill-la-kill-2013.jpg",
    type: "anime",
  },
  {
    id: "little-witch-academia",
    title: "Little Witch Academia",
    poster: "/assets/images/animes/little-witch-academia-2017.jpg",
    video: "/assets/videos/little-witch-academia.mp4",
    type: "anime",
  },
  {
    id: "perfect-blue",
    title: "Perfect Blue",
    poster: "/assets/images/animes/perfect-blue-1998.jpg",
    video: "/assets/videos/perfect-blue.mp4",
    type: "anime",
  },
  {
    id: "steins-gate",
    title: "Steins;Gate",
    poster: "/assets/images/animes/steins-gate-2011.jpg",
    video: "/assets/videos/steins-gate.mp4",
    type: "anime",
  },
];
