import { Item } from "./types";

export const movieItems: Item[] = [
  {
    id: "a-time-to-kill",
    title: "A Time to Kill",
    poster: "/assets/images/movies/a-time-to-kill-1996.jpg",
    video: "/assets/videos/a-time-to-kill-trailer.mp4",
    type: "movie",
  },
  {
    id: "the-godfather",
    title: "The Godfather",
    poster: "/assets/images/movies/the-godfather-1972.jpg",
    video: "/assets/videos/the-godfather-trailer.mp4",
    type: "movie",
  },
  {
    id: "fallen-angels",
    title: "Fallen Angels",
    poster: "/assets/images/movies/fallen-angels-1995.jpg",
    video: "/assets/videos/fallen-angels-trailer.mp4",
    type: "movie",
  },
  {
    id: "amadeus",
    title: "Amadeus",
    poster: "/assets/images/movies/amadeus-1984.jpg",
    video: "/assets/videos/amadeus-trailer.mp4",
    type: "movie",
  },
  {
    id: "john-wick-2",
    title: "John Wick: Chapter 2",
    poster: "/assets/images/movies/john-wick-chapter-2-2017.jpg",
    video: "/assets/videos/john-wick-chapter-2-trailer.mp4",
    type: "movie",
  },
  {
    id: "ip-man",
    title: "Ip Man",
    poster: "/assets/images/movies/ip-man-2008.jpg",
    video: "/assets/videos/ip-man-trailer.mp4",
    type: "movie",
  },
  {
    id: "shawshank-redemption",
    title: "Shawshank Redemption",
    poster: "/assets/images/movies/the-shawshank-redemption-1994.jpg",
    video: "/assets/videos/the-shawshank-redemption-trailer.mp4",
    type: "movie",
  },
  {
    id: "butterfly-effect",
    title: "Butterfly Effect",
    poster: "/assets/images/movies/the-butterfly-effect-2004.jpg",
    video: "/assets/videos/the-butterfly-effect-trailer.mp4",
    type: "movie",
  },
  {
    id: "imitation-game",
    title: "The Imitation Game",
    poster: "/assets/images/movies/the-imitation-game-2014.jpg",
    video: "/assets/videos/the-imitation-game-trailer.mp4",
    type: "movie",
  },
  {
    id: "parasite",
    title: "Parasite",
    poster: "/assets/images/movies/parasite-2019.jpg",
    video: "/assets/videos/parasite-trailer.mp4",
    type: "movie",
  },
  {
    id: "back-to-the-future",
    title: "Back To The Future",
    poster: "/assets/images/movies/back-to-the-future-1985.jpg",
    video: "/assets/videos/back-to-the-future-trailer.mp4",
    type: "movie",
  },
  {
    id: "beverly-hills-cop",
    title: "Beverly Hills Cop",
    poster: "/assets/images/movies/beverly-hills-cop-1984.jpg",
    video: "/assets/videos/beverly-hills-cop-trailer.mp4",
    type: "movie",
  },
  {
    id: "escape-from-new-york",
    title: "Escape From New York",
    poster: "/assets/images/movies/escape-from-new-york-1981.jpg",
    video: "/assets/videos/escape-from-new-york-trailer.mp4",
    type: "movie",
  },
  {
    id: "road-house",
    title: "Road House",
    poster: "/assets/images/movies/road-house-1989.jpg",
    video: "/assets/videos/road-house-trailer.mp4",
    type: "movie",
  },
  {
    id: "they-live",
    title: "They Live",
    poster: "/assets/images/movies/they-live-1988.jpg",
    video: "/assets/videos/they-live-trailer.mp4",
    type: "movie",
  },
];
